export function getCountryCode(countryName: string): string {
  const countryMap = {
    'United States': 'US',
    'United States of America': 'US',
    'USA': 'US',
    'Canada': 'CA',
    'United Kingdom': 'GB',
    'UK': 'GB',
    'Great Britain': 'GB',
    'England': 'GB',
    'Scotland': 'GB',
    'Wales': 'GB',
    'Northern Ireland': 'GB',
    'Australia': 'AU',
    'Germany': 'DE',
    'France': 'FR',
    'Italy': 'IT',
    'Spain': 'ES',
    'Netherlands': 'NL',
    'Belgium': 'BE',
    'Switzerland': 'CH',
    'Austria': 'AT',
    'Sweden': 'SE',
    'Norway': 'NO',
    'Denmark': 'DK',
    'Finland': 'FI',
    'Poland': 'PL',
    'Czech Republic': 'CZ',
    'Hungary': 'HU',
    'Romania': 'RO',
    'Bulgaria': 'BG',
    'Greece': 'GR',
    'Portugal': 'PT',
    'Ireland': 'IE',
    'New Zealand': 'NZ',
    'Japan': 'JP',
    'South Korea': 'KR',
    'China': 'CN',
    'India': 'IN',
    'Brazil': 'BR',
    'Mexico': 'MX',
    'Argentina': 'AR',
    'Chile': 'CL',
    'Colombia': 'CO',
    'Peru': 'PE',
    'Venezuela': 'VE',
    'South Africa': 'ZA',
    'Egypt': 'EG',
    'Morocco': 'MA',
    'Tunisia': 'TN',
    'Algeria': 'DZ',
    'Libya': 'LY',
    'Sudan': 'SD',
    'Ethiopia': 'ET',
    'Kenya': 'KE',
    'Nigeria': 'NG',
    'Ghana': 'GH',
    'Senegal': 'SN',
    'Ivory Coast': 'CI',
    'Cameroon': 'CM',
    'Gabon': 'GA',
    'Congo': 'CG',
    'Democratic Republic of the Congo': 'CD',
    'Angola': 'AO',
    'Zambia': 'ZM',
    'Zimbabwe': 'ZW',
    'Botswana': 'BW',
    'Namibia': 'NA',
    'Mozambique': 'MZ',
    'Madagascar': 'MG',
    'Mauritius': 'MU',
    'Seychelles': 'SC',
    'Comoros': 'KM',
    'Mayotte': 'YT',
    'Reunion': 'RE',
    'Saint Helena': 'SH',
    'Ascension': 'AC',
    'Tristan da Cunha': 'TA',
    'Falkland Islands': 'FK',
    'South Georgia': 'GS',
    'South Sandwich Islands': 'GS',
    'Antarctica': 'AQ',
    'Greenland': 'GL',
    'Iceland': 'IS',
    'Faroe Islands': 'FO',
    'Svalbard': 'SJ',
    'Jan Mayen': 'SJ',
    'Bouvet Island': 'BV',
    'Heard Island': 'HM',
    'McDonald Islands': 'HM',
    'French Southern Territories': 'TF',
    'British Indian Ocean Territory': 'IO',
    'Christmas Island': 'CX',
    'Cocos Islands': 'CC',
    'Norfolk Island': 'NF',
    'Pitcairn': 'PN',
    'Tokelau': 'TK',
    'Niue': 'NU',
    'Cook Islands': 'CK',
    'Wallis and Futuna': 'WF',
    'French Polynesia': 'PF',
    'New Caledonia': 'NC',
    'Vanuatu': 'VU',
    'Solomon Islands': 'SB',
    'Papua New Guinea': 'PG',
    'Fiji': 'FJ',
    'Tonga': 'TO',
    'Samoa': 'WS',
    'American Samoa': 'AS',
    'Guam': 'GU',
    'Northern Mariana Islands': 'MP',
    'Micronesia': 'FM',
    'Marshall Islands': 'MH',
    'Palau': 'PW',
    'Nauru': 'NR',
    'Kiribati': 'KI',
    'Tuvalu': 'TV',
    'East Timor': 'TL',
    'Timor-Leste': 'TL',
    'Brunei': 'BN',
    'Malaysia': 'MY',
    'Singapore': 'SG',
    'Thailand': 'TH',
    'Cambodia': 'KH',
    'Laos': 'LA',
    'Vietnam': 'VN',
    'Myanmar': 'MM',
    'Bangladesh': 'BD',
    'Sri Lanka': 'LK',
    'Maldives': 'MV',
    'Pakistan': 'PK',
    'Afghanistan': 'AF',
    'Iran': 'IR',
    'Iraq': 'IQ',
    'Kuwait': 'KW',
    'Saudi Arabia': 'SA',
    'Bahrain': 'BH',
    'Qatar': 'QA',
    'United Arab Emirates': 'AE',
    'Oman': 'OM',
    'Yemen': 'YE',
    'Jordan': 'JO',
    'Syria': 'SY',
    'Lebanon': 'LB',
    'Israel': 'IL',
    'Palestine': 'PS',
    'Cyprus': 'CY',
    'Turkey': 'TR',
    'Georgia': 'GE',
    'Armenia': 'AM',
    'Azerbaijan': 'AZ',
    'Russia': 'RU',
    'Ukraine': 'UA',
    'Belarus': 'BY',
    'Lithuania': 'LT',
    'Latvia': 'LV',
    'Estonia': 'EE',
    'Moldova': 'MD',
    'Slovakia': 'SK',
    'Slovenia': 'SI',
    'Croatia': 'HR',
    'Bosnia and Herzegovina': 'BA',
    'Serbia': 'RS',
    'Montenegro': 'ME',
    'Kosovo': 'XK',
    'Macedonia': 'MK',
    'Albania': 'AL',
    'Kazakhstan': 'KZ',
    'Uzbekistan': 'UZ',
    'Turkmenistan': 'TM',
    'Kyrgyzstan': 'KG',
    'Tajikistan': 'TJ',
    'Mongolia': 'MN',
    'North Korea': 'KP',
    'Taiwan': 'TW',
    'Hong Kong': 'HK',
    'Macau': 'MO',
    'Philippines': 'PH',
    'Indonesia': 'ID'
  };
  
  return countryMap[countryName as keyof typeof countryMap] || countryName;
}

// Helper function to map US state names to 2-letter codes
export function getStateCode(stateName: string): string {
  // Normalize the input: trim whitespace and convert to lowercase
  const normalizedState = stateName.trim().toLowerCase();
  
  const stateMap = {
    // Full names
    'alabama': 'AL',
    'alaska': 'AK',
    'arizona': 'AZ',
    'arkansas': 'AR',
    'california': 'CA',
    'colorado': 'CO',
    'connecticut': 'CT',
    'delaware': 'DE',
    'florida': 'FL',
    'georgia': 'GA',
    'hawaii': 'HI',
    'idaho': 'ID',
    'illinois': 'IL',
    'indiana': 'IN',
    'iowa': 'IA',
    'kansas': 'KS',
    'kentucky': 'KY',
    'louisiana': 'LA',
    'maine': 'ME',
    'maryland': 'MD',
    'massachusetts': 'MA',
    'michigan': 'MI',
    'minnesota': 'MN',
    'mississippi': 'MS',
    'missouri': 'MO',
    'montana': 'MT',
    'nebraska': 'NE',
    'nevada': 'NV',
    'new hampshire': 'NH',
    'new jersey': 'NJ',
    'new mexico': 'NM',
    'new york': 'NY',
    'north carolina': 'NC',
    'north dakota': 'ND',
    'ohio': 'OH',
    'oklahoma': 'OK',
    'oregon': 'OR',
    'pennsylvania': 'PA',
    'rhode island': 'RI',
    'south carolina': 'SC',
    'south dakota': 'SD',
    'tennessee': 'TN',
    'texas': 'TX',
    'utah': 'UT',
    'vermont': 'VT',
    'virginia': 'VA',
    'washington': 'WA',
    'west virginia': 'WV',
    'wisconsin': 'WI',
    'wyoming': 'WY',
    'district of columbia': 'DC',
    'american samoa': 'AS',
    'guam': 'GU',
    'northern mariana islands': 'MP',
    'puerto rico': 'PR',
    'united states minor outlying islands': 'UM',
    'u.s. virgin islands': 'VI',
    'virgin islands': 'VI',
    
    // Common abbreviations and variations
    'nd': 'ND',
    'sd': 'SD',
    'nc': 'NC',
    'sc': 'SC',
    'va': 'VA',
    'wa': 'WA',
    'wv': 'WV',
    'wi': 'WI',
    'wy': 'WY',
    'al': 'AL',
    'ak': 'AK',
    'az': 'AZ',
    'ar': 'AR',
    'ca': 'CA',
    'co': 'CO',
    'ct': 'CT',
    'de': 'DE',
    'fl': 'FL',
    'ga': 'GA',
    'hi': 'HI',
    'id': 'ID',
    'il': 'IL',
    'in': 'IN',
    'ia': 'IA',
    'ks': 'KS',
    'ky': 'KY',
    'la': 'LA',
    'me': 'ME',
    'md': 'MD',
    'ma': 'MA',
    'mi': 'MI',
    'mn': 'MN',
    'ms': 'MS',
    'mo': 'MO',
    'mt': 'MT',
    'ne': 'NE',
    'nv': 'NV',
    'nh': 'NH',
    'nj': 'NJ',
    'nm': 'NM',
    'ny': 'NY',
    'oh': 'OH',
    'ok': 'OK',
    'or': 'OR',
    'pa': 'PA',
    'ri': 'RI',
    'tn': 'TN',
    'tx': 'TX',
    'ut': 'UT',
    'vt': 'VT',
    'dc': 'DC',
    'as': 'AS',
    'gu': 'GU',
    'mp': 'MP',
    'pr': 'PR',
    'um': 'UM',
    'vi': 'VI',
  };
  
  return stateMap[normalizedState as keyof typeof stateMap] || stateName;
}
